version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: valley3
      POSTGRES_DB: material_db
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - c:\Users\User\Desktop\battery-material-info\work:/work
    ports:
      - "8888:8888"

    links:
      - postgres
    
    depends_on:
      - postgres

secrets:
  postgres_password:
    file: ./postgres_password.txt

volumes:
  postgres_data:
